# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/AppCover.qml) \
        $$quote($$BASEDIR/assets/about.qml) \
        $$quote($$BASEDIR/assets/image/bbIcon.png) \
        $$quote($$BASEDIR/assets/image/bos.png) \
        $$quote($$BASEDIR/assets/image/greyIcon.png) \
        $$quote($$BASEDIR/assets/image/ic_add.png) \
        $$quote($$BASEDIR/assets/image/ic_cancel.png) \
        $$quote($$BASEDIR/assets/image/ic_clear.png) \
        $$quote($$BASEDIR/assets/image/ic_compose.png) \
        $$quote($$BASEDIR/assets/image/ic_contact.png) \
        $$quote($$BASEDIR/assets/image/ic_copy.png) \
        $$quote($$BASEDIR/assets/image/ic_doctype_music.png) \
        $$quote($$BASEDIR/assets/image/ic_doctype_video.png) \
        $$quote($$BASEDIR/assets/image/ic_email_dk.png) \
        $$quote($$BASEDIR/assets/image/ic_expand.png) \
        $$quote($$BASEDIR/assets/image/ic_favorite.png) \
        $$quote($$BASEDIR/assets/image/ic_help.png) \
        $$quote($$BASEDIR/assets/image/ic_info.png) \
        $$quote($$BASEDIR/assets/image/ic_microphone.png) \
        $$quote($$BASEDIR/assets/image/ic_next.png) \
        $$quote($$BASEDIR/assets/image/ic_overflow_action.png) \
        $$quote($$BASEDIR/assets/image/ic_paste.png) \
        $$quote($$BASEDIR/assets/image/ic_pause.png) \
        $$quote($$BASEDIR/assets/image/ic_play.png) \
        $$quote($$BASEDIR/assets/image/ic_previous.png) \
        $$quote($$BASEDIR/assets/image/ic_reload.png) \
        $$quote($$BASEDIR/assets/image/ic_select_text.png) \
        $$quote($$BASEDIR/assets/image/ic_settings.png) \
        $$quote($$BASEDIR/assets/image/ic_share.png) \
        $$quote($$BASEDIR/assets/image/ic_show_vkb.png) \
        $$quote($$BASEDIR/assets/image/ic_stop.png) \
        $$quote($$BASEDIR/assets/image/icon.png) \
        $$quote($$BASEDIR/assets/image/icon120.png) \
        $$quote($$BASEDIR/assets/image/icon180.png) \
        $$quote($$BASEDIR/assets/image/icon240.png) \
        $$quote($$BASEDIR/assets/image/icon80.png) \
        $$quote($$BASEDIR/assets/image/uNote.png) \
        $$quote($$BASEDIR/assets/image/youtube.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/settings.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/appsettings.cpp) \
        $$quote($$BASEDIR/src/encode.cpp) \
        $$quote($$BASEDIR/src/keyboard.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/applicationui.hpp) \
        $$quote($$BASEDIR/src/appsettings.h) \
        $$quote($$BASEDIR/src/encode.hpp) \
        $$quote($$BASEDIR/src/keyboard.h)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/image/*.qml) \
        $$quote($$BASEDIR/../assets/image/*.js) \
        $$quote($$BASEDIR/../assets/image/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
